//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRental_Entity : DbContext
    {
        public CarRental_Entity()
            : base("name=CarRental_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarRental_Records> CarRental_Records { get; set; }
        public virtual DbSet<CarRental_Roles> CarRental_Roles { get; set; }
        public virtual DbSet<CarRental_TypesOfCars> CarRental_TypesOfCars { get; set; }
        public virtual DbSet<CarRental_UserRoles> CarRental_UserRoles { get; set; }
        public virtual DbSet<CarRental_Users> CarRental_Users { get; set; }
    }
}
