//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRental_UserRoles
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual CarRental_Roles CarRental_Roles { get; set; }
        public virtual CarRental_Users CarRental_Users { get; set; }
    }
}
